<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php $_order = $block->getOrderItemsDetails(); ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
<?php
$shipping_addresses = $_order->getShippingAddress()->getData();
$billing_addresses = $_order->getBillingAddress()->getData();
?>
<table>
    <tr><td>Shipping Address</td><td><?php print_r($shipping_addresses); ?></td></tr>
    <tr><td>Billing Address</td><td><?php print_r($billing_addresses); ?></td></tr>
    <tr><td>Sub Total</td><td><?php echo $_order->formatPrice($_order->getSubTotal()); ?></td>
    <tr><td>Shipping & Handling</td><td><?php echo $_order->formatPrice($_order->getShippingAmount()); ?></td>
    <tr><td>Grand Total</td><td><?php echo $_order->formatPrice($_order->getGrandTotal()); ?></td></tr>
</table>

